version: "3.8"

services:
  react-app-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${environment}
    container_name: react-app-prod
    image: tamako8782/mytodoapp:front-prodv1
    volumes:
      - ./frontend/myapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true

#####go
  go-app-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${environment}
    container_name: go-app-prod
    image: tamako8782/mytodoapp:back-prodv2
    volumes:
    - ./backend/:/app/
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_PORT=${MYSQL_PORT:-3306}"
#####mysql(ビルドするだけなんでこれは不要)
##  db-prod:
##    image: mysql:8.2.0
##    container_name: yama-db
##    volumes:
##      - ./backend/dbvol/data/db:/var/lib/mysql
##    environment: 
##      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
##      - "MYSQL_USER=${MYSQL_USER}"
##      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
##      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
##      - TZ=Asia/Tokyo
##    ports:
##      - "3306:3306"

#####migrate
  db-migrate-prod:
    build: 
      context: ./backend/dbvol/migrate 
      target: ${environment}
    
    image: tamako8782/mytodoapp:db-migrate-prodv2
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "WAIT_HOSTS= ${MYSQL_HOST}:3306"
      - "MIGRATIONS_DIR= /migrations"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
          - ./backend/dbvol/migrate:/migrations
      