apiVersion: v1
kind: Secret
metadata:
  name: yama-secret
type: Opaque
data:
  MYSQL_DATABASE: eWFtYW15c3Fs
  MYSQL_HOST: eWFtYS1kYg==
  MYSQL_USER: YXBw
  MYSQL_PASSWORD: YWRtaW4xMjM0IQ==
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM0IQ==
