name: Go Unit Tests

on:
  push:
    branches:
      - develop


jobs:
  Go-UnitTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/src
    services:
      mysql:
        image: mysql:8.2
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: |
          echo "Listing files in current directory:"
          ls -R

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 1
          done

      - name: Run Go test
        run: go test -v ./repositories
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_HOST: "localhost"
