name: Kubernetes Manifest Validation

on:
  push:
    paths:
      - 'k8s/manifest_2/**'  # k8s/manifest_2配下の変更時にトリガー
  pull_request:
    paths:
      - 'k8s/manifest_2/**'  # PR時にもトリガー

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Goをセットアップ
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # 必要なGoのバージョンを指定

    # 3. Kustomizeをインストール
    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        sudo mv kustomize /usr/local/bin/

    # 4. KubeconformをGoでインストール
    - name: Install Kubeconform with Go
      run: |
        go install github.com/yannh/kubeconform/cmd/kubeconform@v0.4.13
      env:
        GOBIN: ${{ github.workspace }}/bin
        PATH: ${{ github.workspace }}/bin:${{ env.PATH }}

    # 5. basesディレクトリのバリデーション
    - name: Validate bases with Kustomize and Kubeconform
      run: |
        kustomize build k8s/manifest_2/bases | kubeconform -strict

    ### 6. stagingオーバーレイのバリデーション (コメントアウトされている)
    ## - name: Validate staging overlay with Kustomize and Kubeconform
    ##   run: |
    ##     kustomize build k8s/manifest_2/overlays/staging | kubeconform -strict

    ### 7. developmentオーバーレイのバリデーション (コメントアウトされている)
    ## - name: Validate development overlay with Kustomize and Kubeconform
    ##   run: |
    ##     kustomize build k8s/manifest_2/overlays/development | kubeconform -strict
